### PR TITLE
Working save game and load game

### PR DESCRIPTION
**Pull request by W84Soft**
Tested on NodeJS 20

How to run it?
Install all package dependencies:
npm i

Now you can start server on port 80
node index.js
or
npm run start

### CODE REVIEW

**Comment by MeterPreter57** [comment]
Hi there, I’ve tested and it really works. Great job!
This is a single player version of the game so I guess the multiplayer version should be in a separate repo because you can’t play it offline and some people do that.

**Comment by W84Soft** [comment]
If you think so, we can probably do multiplayer on the new repository. 

I'm wondering whether to try to modify c2runtime.js so that each request is handled by localStorage instead of the server. 
This way, anyone who wants to play won't have to download the game in ElectronJS or install nodeJS.

**Comment by MeterPreter57** [comment]
I created a new repo with all the files from the original multiplayer version. https://github.com/MeterPreter57/minidayz-multiplayer

**Comment by MeterPreter57** [comment]
I will merge game saving here and add your instructions to readme.
I don't think that this will work with github-pages (but I may be wrong). Handling requests with local storage can make it possible?

**Comment by W84Soft** [comment]
Yes, handling requests via localStorage will eliminate the problem with github-pages.

I will make a new pull request with request handling via localstorage :)

**Pull request closed without merging**
